### ISSUE TITLE
Fix [@genType "MyComponent] Annotation

### ISSUE THREAD

**Issue by peterpme** [reason-association/genType#422]
As we talked about over Discord (Thank you!):

`[@genType "Button"]` seems to be broken. The result should equal the same result as running:

```reason
[@genType]
[@genType.as "Button"]
```

In Button.gen.js, I should see:

```js
export const Button = ButtonBs.make
```

Thanks!

**Comment by cristianoc** [comment]
Thank you @peterpme for the report.
Offending diff: https://github.com/cristianoc/genType/commit/9d6291a782aa8c150b0fee33a24a4efab9923f0a

**Comment by cristianoc** [comment]
Plan:
- re-introduce the feature, as an abbreviation for the double annotation
- document it
- make it compatible with the warning on unused payloads

**Comment by cristianoc** [comment]
@peterpme  I might need a better repro, as the example in https://github.com/cristianoc/genType/pull/423 seems to work.
It issues a warning, but that's a separate issue -- I will remove the warning.

**Comment by cristianoc** [comment]
Can you give a small self contained repro?

**Comment by peterpme** [comment]
Hey Cristiano very sorry about the delay, I got overwhelmed at work.

No problem! Here's what I have inside my repo. Maybe I'm just doing something wrong so just want to get your opinion before I create it.

Javascript import file (this used to work):
```js
import { Loading } from "components/PropertiesPanel/PropertiesPanelUtils.gen";
```

gentype 3.12: (this works with above implementation!)
```
/* Untyped file generated from PropertiesPanelUtils.re by genType. */
/* eslint-disable */

import * as PropertiesPanelUtilsBS from './PropertiesPanelUtils.bs';

export const Loading_Loading = PropertiesPanelUtilsBS.Loading.make;

export const Loading = PropertiesPanelUtilsBS.Loading
```

gentype 3.22: (this is broken!)

```
/* Untyped file generated from PropertiesPanelUtils.re by genType. */
/* eslint-disable */

import * as PropertiesPanelUtilsBS from './PropertiesPanelUtils.bs';

export const Loading_Loading = PropertiesPanelUtilsBS.Loading.make;
```

This is Loading component inside PropertiesPanelUtils.re:

```re
module Loading = {
  [@genType "Loading"]
  [@react.component]
  let make = () => {
    <div className="flex justify-center align-center">
      <LoadingSpinner className="mt-4" inline=true size=30 />
    </div>;
  };
};
```

**Comment by cristianoc** [comment]
@peterpme is this a different thing than the current issue?

**Comment by cristianoc** [comment]
Looks more related to `https://github.com/cristianoc/genType/pull/416`.
Would you open another issue for that?

**Comment by cristianoc** [comment]
For the original issue, would you let me know
- wherther `[@genType] [@genType.as "Button"]` works.
- whether `[@genType.as "Button"]` alone works.

**Comment by cristianoc** [comment]
I think just using `[@genType.as "Button"]` works, and gives no warnings.
On that optimistic assumption, closing for now.
