### ISSUE TITLE
GenType not quoting object keys which require quoting

### ISSUE THREAD

**Issue by benadamstyles** [reason-association/genType#431]
Hi, would love to PR but I think this project is still a little too complex for me. Issue is simple though (even if the fix isn't):

```reason
[@genType]
type t = {
  [@bs.as "the-key"]
  theKey: string,
}
```
when converted to flow, results in:
```js
export type t = {| +the-key: string |};
```
which is obviously not valid JS. It should be:
```js
export type t = {| +'the-key': string |};
```

**Comment by cristianoc** [comment]
@benadamstyles thanks for the report!
I have added a single debug line here:
https://github.com/reason-association/genType/pull/432

Feel free to continue the PR from there if you'd like, as it should be self explanatory.
Or, I can also do it.

**Comment by benadamstyles** [comment]
Great thanks, I'll have a go!
