### ISSUE TITLE
ReactShim in examples doesn't expose newly added `React.ref` type

### ISSUE THREAD

**Issue by bsansouci** [reason-association/genType#439]
Seems like the new version of reason-react adds `React.ref` but the shims haven't been updated yet! 
Not totally sure what the simplest shim type is for ref, I added
```ts
// tslint:disable-next-line:max-classes-per-file
export abstract class ref<T> { }
```
... lol

**Comment by cristianoc** [comment]
@bsansouci thanks, I had not noticed the change from `React.Ref.t` to `React.ref`.
That type is built-in so I'll just add the one-liner internally.
