### ISSUE TITLE
@genType.as broken on Variants in BS 8.2

### ISSUE THREAD

**Issue by benadamstyles** [reason-association/genType#447]
This is the output from the following Reason code when running genType `v3.30.0` and bs-platform `v8.2.0`:

```reason
// .re

[@genType "Course"]
type t =
  | [@genType.as "main"] Main
  | [@genType.as "starter"] Starter
  | [@genType.as "dessert"] Dessert
  | [@genType.as "side"] Side;

[@genType]
let displayOrderCourses: array(t) = [|Starter, Main, Side, Dessert|];
```

```js
// .bs.js

var displayOrderCourses = [
  /* Starter */1,
  /* Main */0,
  /* Side */3,
  /* Dessert */2
];
```

```js
// .gen.js

export const displayOrderCourses: Array<t> = CoursesBS.displayOrderCourses.map(function _element(ArrayItem: $any) { return ArrayItem});
```

Previously, the output was:
```js
// .gen.js

const $$toJS344541656 = {"0": "main", "1": "starter", "2": "dessert", "3": "side"};

export const displayOrderCourses: Array<t> = CoursesBS.displayOrderCourses.map(function _element(ArrayItem: $any) { return $$toJS344541656[ArrayItem]});
```

Hopefully it's clear what the issue is, but basically genType is no longer generating a conversion function to turn the Variants (encoded as `int`s) back into strings.

**Comment by cristianoc** [comment]
Thanks I’ll check when I’m back next week.
Sure it’s ordinary `Variants` and not `’polymorphic` ones?

**Comment by benadamstyles** [comment]
Actually I think it's happening with polymorphic ones too:

```reason
[@genType]
type clearButtonMode = [
  | `always
  | `never
  | [@genType.as "unless-editing"] `unlessEditing
  | [@genType.as "while-editing"] `whileEditing
];
```

is now compiled to:

```js
export type clearButtonMode = 
    "always"
  | "never"
  | "unlessEditing"
  | "whileEditing";
```

whereas before it was:

```js
export type clearButtonMode = 
    "always"
  | "never"
  | "unless-editing"
  | "while-editing";
```

**Comment by benadamstyles** [comment]
Just an update, I tried switching to `@bs.as` to get the old genType behavior in BuckleScript natively, but that's actually not supported currently – BS cannot represent polymorphic variants as string literals with hyphens in them: https://github.com/BuckleScript/bucklescript/issues/4595

**Comment by cristianoc** [comment]
@benadamstyles this is fixed in BuckleScript/bucklescript#4595.

Notice conversion for poly variants is not supported yet for bucklescript 8.2. The reason is that renaming with `@genType.as` would be the only case in which runtime conversion is still required. I was wondering whether it is actually used, before even deprecating it.

**Comment by benadamstyles** [comment]
That's brilliant, thanks.

I use `@genType.as` for poly variants extensively throughout my codebase, and as the issue you linked to mentions, any user of reason react native is likely to, until bucklescript supports "string literal" renaming.

**Comment by cristianoc** [comment]
`genType.as` will stay to guarantee compatibility, and will eventually become unnecessary

**Comment by cristianoc** [comment]
In release 3.31.

**Comment by benadamstyles** [comment]
Incredible 😃

Thank you so much!
