### ISSUE TITLE
allow default export

### ISSUE THREAD

**Issue by jfrolich** [reason-association/genType#448]
```
[@genType "default"]
let make ...
```
The above currently result in a parse error. It would be nice of genType to support creating a default export.

**Comment by cristianoc** [comment]
@jfrolich default export already exists in bucklescript, and genType simply plays along with it:
```
[@genType]
let default = make

**Comment by jfrolich** [comment]
> @jfrolich default export already exists in bucklescript, and genType simply plays along with it:
> 
> ```
> [@genType]
> let default = make
> ```

Yes that's what I've been doing. But I though it might be great to have `[@genType "default"]` then we don't have the default alias in Reason.
