### ISSUE TITLE
React forwardRef breaks when component props include a polyvariant

### ISSUE THREAD

**Issue by TomiS** [reason-association/genType#463]
Based on some [other](https://github.com/reason-association/genType/issues/247) tickets/discussion I've read I think this is probably already a know issue, but I'll make this ticket just to confirm and discuss about the future. So in short, it seems that when a react component is using one or more polyvariants as a prop, a wrapper createElement call is generated by genType. If that component was also wrapped inside forwardRef, this ref forwarding is now broken when called from javascript because of the stuff generated by genType.

I realize this is probably a difficult corner to fix. What I'm wondering is if the upcoming improvements in ReScript (like redefining how polyvariants are implemented on JS side) will be enough to fix this or will this still be a problem after that?

Note that we're using bs-platform 7.3.2. I don't know if this is already changed in 8.x

Here's also a quite minimal test repo to prove the problem if you happen to need one: https://github.com/TomiS/forwardref/blob/master/src/ReactJsComponent.js#L8

**Comment by cristianoc** [comment]
Does the problem arise when a conversion is required (between the JS and Re representation)? If that's the case, then using poly variants and `8.2` should take care of the problem.

**Comment by TomiS** [comment]
I tested the same code with 8.2.0 and I'm happy to confirm it indeed works. It even works with polyvariants that have payloads. So that change indeed was an important one, nice work!
