### ISSUE TITLE
Unsafe TS code generated when having an optional named argument and a promise

### ISSUE THREAD

**Issue by vknez** [reason-association/genType#466]
We're using this beautiful tool extensively in two projects, since quite some time, and this the first time we noticed an issue. Thanks for letting us have `genType`!

We noticed that generated TypeScript code fails when trying to call a function and not pass an optional argument. The code expects that the optional argument will be passed, even though TypeScript types state that it is optional. 

This situation might be happening only when there is a promise that `genType` needs to wait for, in order to transform the result before passing it to the BuckleScript's JS code.

Given this ReasonML function:
```reason
[@genType]
let fn = (~x=() => Js.Promise.resolve(Some("a")), ()) => {
  x()
  |> Js.Promise.then_(
       fun
       | Some(_) => Js.Promise.resolve(true)
       | _ => Js.Promise.resolve(false),
     );
};
```

GenType generates the following TypeScript:
```typescript
export const fn: (
  _1: { readonly x?: () => Promise<null | undefined | string> },
  _2: void
) => Promise<boolean> = function (Arg1: any, Arg2: any) {
  const result = Curry._2(
    AuthUtilsBS.fn,
    function () {
      const result1 = Arg1.x();
      return result1.then(function _element($promise: any) {
        return $promise == null ? undefined : $promise;
      });
    },
    Arg2
  );
  return result;
};
```

The code fails because `x` is `undefined` when I try to call the function from the TS side, without providing a value for the optional named argument `x`:
```typescript
fn({});
```

Furthermore, could we in this case avoid needing to pass even the `{}`, since all arguments are optional?

**Comment by cristianoc** [comment]
@vknez good catch!
This should solve it: https://github.com/reason-association/genType/pull/467
Kind of a corner case, triggered only when:
- an optional arg is used
- whether conversion is required or not, depends on whether the conversion is to JS or from JS.

**Comment by vknez** [comment]
Thanks @cristianoc for the promptest fix :) I can confirm it works in the new branch. I hope the new release will be issued soon.

What about the other question regarding being forced to supply an empty object from TypeScript in case all named arguments are optional - would that be easy to change in order to have nicer TypeScript code (`fn()` instead of `fn({})`)?

**Comment by cristianoc** [comment]
@vknez creating a new release `3.37`.
Unsure about special-casing the situation where all the named arguments are optional, and introducing complexity/irregularity for that case. It should be possible to simulate the same by using an optional argument of record type.

**Comment by vknez** [comment]
@cristianoc Thanks!

I suggested being able to write `fn()` instead of `fn({})` just in case it is easy to do. I agree that it is not worth extra complexity. My situation was because of having several optional arguments for inversion of control, so an optional record would not suffice, but there are simple ways to improve this, not relying purely on genType.
