### ISSUE TITLE
Problem with non-unary variants that contain a variant

### ISSUE THREAD

**Issue by chrischen** [reason-association/genType#471]
When returning a non-unary variant that contains at least another variant and other arguments, a runtime error in JS will occur when calling the function that returns this. No errors on the ReasonML side (haven't tested with ReScript).
```reason
module Test = {
  type typeC =
    | C(string)
    | D(string);
  type typeB = {c: typeC};
  type typeD = Int(int);
  type typeE = int;
  type typeA('a) =
    | A('a, int)
    | B('a, int);
	
  type typeF('a) = | F('a) | G('a);
  type typeH = | H(typeD, int) | I(typeD, int);

  /*[@genType.opaque] */ /* This seems to fix it for the non-working cases */
  type typeJ = | J(typeD, typeD);
  type typeK = | K((typeD, typeD));

  /* Doesn't work */
  [@genType]
  let makeABC = (): typeA(typeB) => A({c: C("a string")}, 5);

  /* Works */
  [@genType]
  let makeBC = (): typeB => {c: C("a string")};

  /* Doesn't work */
  [@genType]
  let makeAC = (): typeA(typeC) => A(C("a string"), 5);

  /* Doesn't work */
  [@genType]
  let makeAD = (): typeA(typeD) => A(Int(3), 5);

  /* Works */
  [@genType]
  let makeAE = (): typeA(typeE) => A(3, 5);

  /* Works */
  [@genType]
  let makeFD  = (): typeF(typeD) => F(Int(3));

  /* Doesn't work */
  [@genType]
  let makeHD = (): typeH => H(Int(5), 5);

  /* Doesn't work */
  [@genType]
  let makeJ = (): typeJ => J(Int(5), Int(3));

  /* Works */
  [@genType]
  let makeK = (): typeK => K((Int(5), Int(3)));
};
```

Sample error for makeHD:

```
TypeError: Cannot read property '_0' of undefined

      260 |   const result = MessageBS.Test.makeHD();
      261 |   return result.TAG===0
    > 262 |     ? {tag:"H", value:[[{tag:"Int", value:result[0]._0
}, result[1]]._0, [{tag:"Int", value:result[0]._0}, result[1]]._1]
}
          |                                                     ^
      263 |     : {tag:"I", value:[[{tag:"Int", value:result[0]._0
}, result[1]]._0, [{tag:"Int", value:result[0]._0}, result[1]]._1]
}
      264 | };
```

Is this supposed to work or is this a bug?

**Comment by cristianoc** [comment]
@chrischen thanks for the report! Indeed there are issues in the conversion of non-unary variants that contain a non-trivial payload. The issue manifests from bs 8 representation.

**Comment by chrischen** [comment]
I'm fairly new to the ecosystem, but for these cases should I be avoiding non-unary variant outputs from generated functions and try to simplify data types exposed to the Javascript side?

My potential use case was to have a function that creates these complex variant types, and also generate a function that consumes these types so that in the JS side it can treat these types opaquely and not deal with them and just glue the functions together. For this use case will I just have to call the generated BS functions directly?

**Comment by cristianoc** [comment]
@chrischen see fix in https://github.com/reason-association/genType/pull/473.
That should take care of this issue as well as https://github.com/reason-association/genType/issues/472.

Let me know if you see any issues in the code generated: https://github.com/reason-association/genType/pull/473/files#diff-a00f58d32d245179b437dbbc65ed6b05bb8a59bf8949ca105b901916bbd14c1cR1

**Comment by chrischen** [comment]
Yep looks good! Thanks for the fast fix!
