### ISSUE TITLE
Cannot find module './Js_OO.gen' or its corresponding type declarations

### ISSUE THREAD

**Issue by phenax** [reason-association/genType#485]
Where can I find an example of a shim for `Js_OO` module? I feel like there isn't enough documentation and available examples for all the shims needed.

**Comment by cristianoc** [comment]
What's the example? Likely a case that is not supported.

**Comment by phenax** [comment]
```rescript
module SomeModule = {
  type t

  @bs.get external _getter: t => option<string> = "oldID"
  export getter = @bs.this ctx => _getter(ctx)
}
```

**Comment by cristianoc** [comment]
Things like `@bs.get` are  not supported by genType, as they are used when the type of the object is not specified. GenType relies on explicit declarations of the type used, e.g. using an explicit object type.

**Comment by phenax** [comment]
Alright. So to get it working temporarily I'll just shim `Js_OO`. Are the missing features and similar behaviors documented somewhere?

**Comment by cristianoc** [comment]
I can't imagine what benefits one would get in trying to export the getter using genType. Looks like in this case, just `let getter = @bs.this ctx => _getter(ctx)` would do.

**Comment by phenax** [comment]
But, that breaks the abstraction that gentype provides with a `.gen.tsx` file as I would have to use the `.bs.js` file directly to import the module.

**Comment by phenax** [comment]
I've created a JS_OO shim that works around this temporarily. Closing the issue.
