### ISSUE TITLE
' character in types creates invalid TS syntax

### ISSUE THREAD

**Issue by johnridesabike** [reason-association/genType#493]
```res
@gentype
type t' = int
```

Outputs:
```ts
// tslint:disable-next-line:interface-over-type-literal
export type t' = number;
```

Perhaps it should compile to `t$prime`, like how the ReScript compiler treats values with `'` characters?

**Comment by cristianoc** [comment]
@johnridesabike handled here: https://github.com/reason-association/genType/pull/494
