### ISSUE TITLE
existential types produce invalid TS

### ISSUE THREAD

**Issue by johnridesabike** [reason-association/genType#502]
```res
@gentype
type rec t = Any('a): t
```
output:
```ts
export type t = { tag: "Any"; value: a };
```

```
Cannot find name 'a'.
Property 'value' of exported interface has or is using private name 'a'.
```

**Comment by cristianoc** [comment]
There's no support for exporting GADTs at the moment. It's not clear what TS type they would map to.

**Comment by johnridesabike** [comment]
Would it be possible for gentype to output type names like `any` or `unknown` for cases that aren’t supported? Or could it print a warning/error so the user can work around it? Either way, silently outputting invalid syntax seems unideal.

**Comment by cristianoc** [comment]
Indeed, it makes sense to give a warning in this case.
Doing it here: https://github.com/reason-association/genType/pull/504
Also, exporting it as opaque in that case, so it's a black box from TS.
